policy_id = _CDDL_CODEGEN_RAW_BYTES_TYPE_
asset_name = _CDDL_CODEGEN_EXTERN_TYPE_
keyhash = _CDDL_CODEGEN_RAW_BYTES_TYPE_ ; @name Ed25519KeyHash
transaction_input = _CDDL_CODEGEN_EXTERN_TYPE_

int64 = -9223372036854775808 .. 9223372036854775807 ; @no_alias

owner =
    keyhash                     ; @name PKH
  / [policy_id, asset_name]     ; @name NFT
  / asset_name                  ; @name Receipt

status =
    0                           ; @name Locked
  / { out_ref: transaction_input
    , for_how_long: int64
    }            ; @name Unlocking

state =
    [ owner: owner
    , status: status
    ]
