[package]
name = "projected-nft-structs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cml-core = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", rev = "802e663f066499ffc3eebdadf76e16873f0fc310" }
cml-chain = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", rev = "802e663f066499ffc3eebdadf76e16873f0fc310" }
cml-crypto = { git = "https://github.com/dcSpark/cardano-multiplatform-lib.git", rev = "802e663f066499ffc3eebdadf76e16873f0fc310" }

cbor_event = "2.4.0"
linked-hash-map = "0.5.3"
derivative = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"
schemars = "0.8.8"
hex = "0.4.3"
