name: Aiken linter and unit tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.0.19-alpha

      - run: aiken fmt ./cardano --check
      - run: aiken check ./cardano
      - run: aiken build ./cardano
